add snippetIdToString
uga-rosa/denippet.vim pull request #22
Opened 2024-05-09 10:58 UTC by ryoppippi

Related to: https://github.com/uga-rosa/cmp-denippet/pull/2

Create method called `snippetIdToString` to get body from snippet id

2024-05-12 11:35 UTC, uga-rosa requested changes

2024-05-12 11:35 UTC, uga-rosa commented on denops/denippet/main.ts
> +      const parsed = lsputil.parseSnippet(id);
A snippet ID is UUID.
https://github.com/uga-rosa/denippet.vim/blob/c0a74b0f84069bbd73f4676da72e3920d9560f39/denops/denippet/loader.ts#L100-L102

It should be the body of the snippet that is passed to `parseSnippet()`.

2024-05-12 15:14 UTC, uga-rosa commented on denops/denippet/main.ts
> +      const parsed = lsputil.parseSnippet(id);
```typescript
    async snippetIdToString(idU: unknown): Promise<string> {
      const id = u.ensure(idU, is.String);
      const { body, matched } = await searchSnippet(loader, id);
      if (body == null) {
        throw new Error(`Unknown snippet id: ${id}`);
      }
      const bodyStr = is.String(body) ? body : await body(denops, matched);
      const parsedBody = lsputil.parseSnippet(bodyStr);
      if (parsedBody === "") {
        throw new Error(`Failed parsing: ${bodyStr}`);
      }
      return parsedBody;
    },
```

2024-05-12 15:20 UTC, uga-rosa commented
`body` and `str` are different concepts.
`body` is `console.log($0)`, str is `console.log()`, etc. `str` is for use in documentation, etc. As far as cmp-denippet is concerned, what you want to add seems to be an `id->body` function. In that case, you should name the function `snippetIdToBody` and remove the `lsputil.parseSnippet` part.

2024-05-12 18:01 UTC, ryoppippi commented
Thanks!
Completed

2024-05-16 15:21 UTC, uga-rosa approved these changes

2024-05-16 15:21 UTC, merged